Session
rpp33-boc-arctic/splitsy pull request #32
Opened 2022-06-07 03:53 UTC by grant350

session is 90% done needs to match with auth user cookie if user cookie exists or enter code new sessionCookie is created. 
AuthCookie.username-> restraunt.js   -> authcookie present -> create new token with same info in db.session;
AuthCookie = null || invalid -> sessioncode present -> look up db sessions with same code || id -> create new token cookie;

authcookie and session code is not present -> find if user is connected to session. if exists create new cookie with same session code else create new session with new session code

2022-06-07 10:37 UTC, neenachcha reviewed
Great job Grant,  One question from me: 
Currently in the the database. 
session_code = 1. --> should this be uuid?
orderId= "00301" --> should this be codeGenerator?

Me and yufang have been using session_code to retrieve data from database. Not sure about Tan, but would be possible to switch them

2022-06-07 22:36 UTC, yfcheng1 requested changes
Great job Grant! I left couple comments on:
1. styles
2. console.log(s)
3. In session route, the user structure seems incorrect
4. there is one session.find code in the route needs checking
5. Do we need the npmignore file?
6. Thanks for implement cors for us

Remember to merge to main again before you push.

2022-06-07 22:36 UTC, yfcheng1 commented on client/src/components/Menu/Menu.js
> +	console.log(props);
Consider remove console.log

2022-06-07 22:36 UTC, yfcheng1 commented on client/src/components/Navbar.js
> +          {this.isAuthenticated? <Link className="bob"  to="/userProfile" style={{color:"white",textDecoration:"none"}}> {this.user} </Link>: null}
Can you add Typography for the {this.user}?  It looks inconsistent.

2022-06-07 22:36 UTC, yfcheng1 commented on client/src/components/Menu/Menu.js
> +console.log(state)
Can you remove this console.log?

2022-06-07 22:36 UTC, yfcheng1 commented on client/src/components/Restaurant/Restaurant.js
> +export {RestaurantPick};
Do you still need this file now?

2022-06-07 22:36 UTC, yfcheng1 commented on client/src/components/Restaurant/rest_pick/map.js
> +        OR
Can you use typescript here?

2022-06-07 22:36 UTC, yfcheng1 commented on client/src/components/Restaurant/rest_pick/list.js
> +       <ListItem key={index} className="item" button style={{height:"150px", border:"1px solid black"}}>
Can you remove the border? or make it grey to match the style

2022-06-07 22:36 UTC, yfcheng1 commented on client/src/components/Restaurant/rest_pick/rest_pick.js
>        <p> Restaurants near me </p>
Can you use typography here?

2022-06-07 22:36 UTC, yfcheng1 commented on server/controllers/orderSession/index.js
> +      users:{username:username,checkout:false,user_cart:[]},
users should be nested objects. Something like:
users: { 
  user_id: {
    username:username,
    checkout:false,
    user_cart:[]
    }
}

2022-06-07 22:36 UTC, yfcheng1 commented on server/controllers/orderSession/index.js
> +  }
What is this session code for?

2022-06-07 22:36 UTC, yfcheng1 commented on server/index.js
> +app.use(cors())
Thanks for implementing cors for us!

2022-06-09 04:54 UTC, closed without merging

2022-06-09 04:55 UTC, yfcheng1 commented
Grant, let me close your pull request and we can merge with Tan's tomorrow! Thanks for the work!